version: '3.8'
services:
  db:
    container_name: planet-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: meze
      POSTGRES_PASSWORD: meze
      POSTGRES_DB: planets-db
    ports:
      - "5432:5432"
